CODEGEN_FILES := $(filter-out $(wildcard codegen/*test.c), $(wildcard codegen/*.c))
CODEGEN_FILES := $(filter-out $(wildcard codegen/cg_*.c), $(CODEGEN_FILES))
CODEGEN_X64_FILES := $(wildcard codegen/*/*.c) $(CODEGEN_FILES)
